### ISSUE TITLE
About releasing code and dataset 

### ISSUE THREAD

**Issue by qkgia** [nianticlabs/stereo-from-mono#1]
Hi, your paper is a brilliant work! Could you please share the MfS dataset and your code? Thanks a lot!

**Comment by JamieWatson683** [comment]
Hi - thanks!

Sure, we are working on code release - aiming for the next few weeks. 

In term of the MfS dataset - we aim to release the monocular predictions (i.e. training labels) for the dataset, but the individual RGB images can be downloaded from the respective web pages, e.g. http://www-personal.umich.edu/~wfchen/depth-in-the-wild/.

Thanks a lot.
