### ISSUE TITLE
No permission in Google Cloud 

### ISSUE THREAD

**Issue by IShengFang** [nianticlabs/stereo-from-mono#10]
I try to download the trained model from Google Cloud, but it shows "Additional permissions required to list objects in this bucket: Ask a bucket owner to grant you 'storage.objects.list' permission."

![Screen Shot 2021-07-01 at 20 38 09](https://user-images.githubusercontent.com/19823525/124125512-42825580-daac-11eb-9a7d-57e00b2be09e.png)

**Comment by JamieWatson683** [comment]
Hi, and thanks for your interest in the project!

Apologies for that - I've just pushed an updated README with new links. Let me know if this works for you.

Thanks a lot.

**Comment by IShengFang** [comment]
The new links work for me.
Thank you.
