### ISSUE TITLE
google colab version

### ISSUE THREAD

**Issue by ugocapeto** [nianticlabs/stereo-from-mono#12]
More a request than an issue but could we have a google colab version of this?

I think that it would benefit a lot of people including me.

It would be nice to be able to easily:
- given a stereo pair, get the depth map.

It would also be nice to be able to:
- given an image and its depth map, get a synthetic image representing the right image or any synthetic image that can be derived from the source image (going left or right and by any amount).

**Comment by daniyar-niantic** [comment]
Hi @ugocapeto 

This repository is mainly provided for replication purposes.
