### ISSUE TITLE
How to run inference on a sample image

### ISSUE THREAD

**Issue by fisakhan** [nianticlabs/stereo-from-mono#13]
Can you please provide a sample code/instruction on how to use the provided pretrained model for generating output of an input image?

**Comment by Entretoize** [comment]
Did you find how to do ? The inference mode seems to search for prepared datasets, it's really not clear...

**Comment by daniyar-niantic** [comment]
Hi @fisakhan .

The inference code is provided for stereo benchmark evaluation: https://github.com/nianticlabs/stereo-from-mono#-evaluation

Depth from a single image is not within the scope of this repo.

Depth from a stereo pair can be computed after refactoring some of the code in this repo.
