### ISSUE TITLE
Generating right side image

### ISSUE THREAD

**Issue by amanseras** [nianticlabs/stereo-from-mono#14]
Good day! Thank you for your work on stereo from mono images. 
I'm trying to generate a right side image from some left image. Currently I am looking at datasets/warp_dataset.py and base_dataset.py. Are these the only files I need if I am only interested in generating right side from a left image? Any help is greatly appreciated. Thank you very much!

**Comment by Asheeshkrsharma** [comment]
Hi @amanseras 
Were you able to generate the right-side images?

**Comment by nikunj-taneja** [comment]
Hi @amanseras same question :)

**Comment by JamieWatson683** [comment]
Hi - really sorry for the delay in getting back to you.

Here is a previous issue discussing how to do this https://github.com/nianticlabs/stereo-from-mono/issues/7.

Let me know if that helps, or if you need some additional advice.

Thanks a lot!
