### ISSUE TITLE
Metrics used for evaluation

### ISSUE THREAD

**Issue by sieme97** [nianticlabs/stereo-from-mono#3]
Hello, your paper is quite interesting. Did you evaluate the proposed method on commonly used metrics such as absolute relative error, RMSE etc?

**Comment by JamieWatson683** [comment]
Hi, thanks for your interest, and sorry. for the slow reply.

Unfortunately no, we did not - we instead opted to use the metrics generally used by the deep stereo community (i.e. metrics on disparity not depth).

I've just pushed an initial code release, so you could adapt the inference code to additionally compute RMSE relatively easily, just make sure to convert all disparities (both predictions and ground truth labels) to depths before computing the scores. 

Thanks a lot,
Jamie
