### ISSUE TITLE
about pretrain model

### ISSUE THREAD

**Issue by xubin1994** [nianticlabs/stereo-from-mono#5]
Hello,can you tell me how much data is used for the pre-training model? I tested it with Intel D435 data, and the result looks not good enough(shown as below),will you provide the link to MFSdataset in the paper?
![image](https://user-images.githubusercontent.com/28856641/101978169-feee0880-3c8d-11eb-912d-95c7c3696f36.png)
![image](https://user-images.githubusercontent.com/28856641/101978147-e41b9400-3c8d-11eb-97e7-c0af7bf7cfe5.png)

**Comment by JamieWatson683** [comment]
Hi - thanks for your question.

Interesting, yes I agree the result doesn't look all that good.

A few questions which might explain it:

- Are the images you feed to the network RGB or grayscale? And what resolution are you running at?
- How well calibrated do the stereo pairs look? Could you maybe post a left and a right image? 
- If you run SGM (or another traditional stereo method), what is the max disparity coming out? Our network should be fairly robust to different baselines/focal lengths,  but if the disparities are very large or very small it may struggle (without retraining for this scenario)

In terms of the MfS dataset - it is a collection of various publicly released datasets, with links given in the README. We will release the disparities used to train (from MiDaS) in the new year (apologies for the delay), but until then you can use their repo to generate the necessary disparities (https://github.com/intel-isl/MiDaS).

Thanks a lot!

**Comment by xubin1994** [comment]
> Hi - thanks for your question.
> 
> Interesting, yes I agree the result doesn't look all that good.
> 
> A few questions which might explain it:
> 
> * Are the images you feed to the network RGB or grayscale? And what resolution are you running at?
> * How well calibrated do the stereo pairs look? Could you maybe post a left and a right image?
> * If you run SGM (or another traditional stereo method), what is the max disparity coming out? Our network should be fairly robust to different baselines/focal lengths,  but if the disparities are very large or very small it may struggle (without retraining for this scenario)
> 
> In terms of the MfS dataset - it is a collection of various publicly released datasets, with links given in the README. We will release the disparities used to train (from MiDaS) in the new year (apologies for the delay), but until then you can use their repo to generate the necessary disparities (https://github.com/intel-isl/MiDaS).
> 
> Thanks a lot!

Hi,thanks for your reply.
I feed to the network graysacle images with resolution 1280 *704;
the images pairs with a maxdisp less than 45;
the images take from the Intel D435i which is well calibrated;
 Stereo pairs is here,and the 0disp_float.png is disp images from D435i，which is scale by 100;
![0-right](https://user-images.githubusercontent.com/28856641/102192873-4ecf0880-3ef6-11eb-808a-d1c729f2bd0e.png)

![0disp_float](https://user-images.githubusercontent.com/28856641/102192859-4aa2eb00-3ef6-11eb-8cd5-eb63468a77ab.png)
![0-left](https://user-images.githubusercontent.com/28856641/102192868-4d9ddb80-3ef6-11eb-864c-13123765bdde.png)

**Comment by JamieWatson683** [comment]
Hi,

Sorry for the delay in getting back to you - yes those do look well calibrated, so that is a good start.

The pretrained model provided was trained to expect far greater disparities (200+), and on mostly RGB images. I've just pushed an update to the README with a link to the MiDaS depths, so I'd suggest trying to retrain the model with the max disparity set to ~45, and convert images to greyscale - that should help to get you more reasonable disparity estimates.

Let me know if you run into any issues with the above!

**Comment by xubin1994** [comment]
> Hi,
> 
> Sorry for the delay in getting back to you - yes those do look well calibrated, so that is a good start.
> 
> The pretrained model provided was trained to expect far greater disparities (200+), and on mostly RGB images. I've just pushed an update to the README with a link to the MiDaS depths, so I'd suggest trying to retrain the model with the max disparity set to ~45, and convert images to greyscale - that should help to get you more reasonable disparity estimates.
> 
> Let me know if you run into any issues with the above!

The data set of Google Cloud is not easy to download, and there is always no speed（0KB） when the downloading  is not completed. Is there any additional download link?

**Comment by daniyar-niantic** [comment]
Hi @xubin1994 . Unfortunately there is no additional download link.

**Comment by daniyar-niantic** [comment]
However, you can generate these depth maps yourself by downloading [MiDaS model](https://github.com/intel-isl/MiDaS) and running it on a collection of images.
