### ISSUE TITLE
where is https://github.com/nianticlabs/ panoptic-forecasting？

### ISSUE THREAD

**Issue by T1aNS1R** [nianticlabs/stereo-from-mono#9]
where is https://github.com/nianticlabs/ panoptic-forecasting？

**Comment by mdfirman** [comment]
Thanks for your interest – it will be coming in the next few days. I'll update here when it does.

Thanks

Michael

**Comment by mdfirman** [comment]
We now have a placeholder for https://github.com/nianticlabs/panoptic-forecasting

The main code release will happen before CVPR.

Thanks

**Comment by daniyar-niantic** [comment]
@T1aNS1R panoptic-forecasting repo is up now.
